### Создание справочника
POST {{gateway_url}}/dictionaries
Authorization: Bearer {{admin-access_token}}
Content-Type: application/json;charset=utf-8

{
  "mnemonic": "ECategoriesTypes2",
  "description": "Виды креативных площадок",
  "items": [
    {
      "name": "ART",
      "value": "Арт"
    },
    {
      "name": "ARCHITECTURE",
      "value": "Архитектура"
    },
    {
      "name": "GAMES_SOFTWARE",
      "value": "Видеоигры и ПО"
    },
    {
      "name": "DESIGN",
      "value": "Дизайн"
    }
  ]
}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

### Получение справочников
GET {{gateway_url}}/open/dictionaries

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Получение значений справочников
GET {{gateway_url}}/open/dictionaries/ECategoriesTypes2

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}


### Добавление значений к справочнику
PUT {{gateway_url}}/dictionaries/ECategoriesTypes2
Authorization: Bearer {{admin-access_token}}
Content-Type: application/json;charset=utf-8

{
  "name": "MUSIC",
  "value": "Музыка"
}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 201, "Response status is not 201");
    });
%}

### Получение значений справочников
GET {{gateway_url}}/open/dictionaries/ECategoriesTypes2

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Удаление справочника
DELETE {{gateway_url}}/dictionaries/ECategoriesTypes2
Authorization: Bearer {{admin-access_token}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Получение справочников
GET {{gateway_url}}/open/dictionaries

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Получение значений справочников
GET {{gateway_url}}/open/dictionaries/ECategoriesTypes2

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 400, "Response status is not 400");
        client.assert(response.body.code === 'LDR-01001', "Response error code must be LDR-01001");
    });
%}
