name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: py-actions/py-dependency-install@v4
        with:
          path: src/backend/requirements.txt
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install idna certifi psycopg2 urllib3
      - run: python src/backend/tests.py

